{% set name = "sbol_factory" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SynBioDex/sbol_factory/archive/v{{ version }}.tar.gz
  sha256: f2e9f92eb4ba614835cb9dfca30926b49bd4bed96b5fceac5717acba0880254c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pysbol3 >=1.0.1
    - sparqlwrapper >=1.8.5
    - pyshacl >=0.13.3
    - python-dateutil >=2.8.1
    - requests
    - python-graphviz
    - pylatex
    - PyPDF2

test:
  requires:
    - python {{ python_min }}
  source_files:
    - test
  imports:
    - {{ name|lower }}
  commands:
    - python -m unittest discover -s test

about:
  home: https://github.com/SynBioDex/sbol_factory
  summary: Provides a mechanism for automatically generating an interactive, object-oriented API from a declarative data model specification encoded in OWL.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kenza12
    - breakthewall
    - tduigou
